export const types = {
    DESTROY_SESSION: 'DESTROY_SESSION',
    //global
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    ACTIVE_FOOTER_INDEX: 'ACTIVE_FOOTER_INDEX',

    TOGGLE_CAMERA_GALLERY_OPTION_MODAL: 'TOGGLE_CAMERA_GALLERY_OPTION_MODAL',
    TOGGLE_SUCCESS_MODAL: 'TOGGLE_SUCCESS_MODAL',
    SET_SUCCESS_MESSAGE: 'SET_SUCCESS_MESSAGE',
    RE_RENDER_APP_STACK: 'RE_RENDER_APP_STACK',
    //home
    SET_CLASS_LIST: 'SET_CLASS_LIST',
    //authentication
    SIGN_UP: 'SIGN_UP',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    //get upcoming classes
    GET_UPCOMING_CLASSES: 'GET_UPCOMING_CLASSES',
    // set upcoming class
    SET_UPCOMING_CLASSES: 'SET_UPCOMING_CLASSES',
    // get class Boooking
    GET_CLASS_BOOKING: 'GET_CLASS_BOOKING',
    //set Booking classes
    SET_BOOKING_CLASSES: 'SET_BOOKING_CLASSES',
    //update meeting link
    UPDATE_MEETING_LINK: ' UPDATE_MEETING_LINK',

    //Create Class
    CREATE_CLASS: 'CREATE_CLASS',
    CREATE_GROUP_CLASS: 'CREATE_GROUP_CLASS',
    SET_CLASS_TYPE_LIST: 'SET_CLASS_TYPE_LIST',
    GET_CLASS_TYPE_LIST: 'GET_CLASS_TYPE_LIST',
    CREATE_CLASS_TAB_INDEX: 'CREATE_CLASS_TAB_INDEX',
    SET_AVAILABILTY: 'SET_AVAILABILTY',
    GET_CLASS_CREATED_SLOTS: "GET_CLASS_CREATED_SLOTS",
    SET_CREATED_CLASS_SLOTS: 'SET_CREATED_CLASS_SLOTS',
    SET_AVAILABILITY_DATE: 'SET_AVAILABILITY_DATE',
    SET_AVAILABILITY_TIME: 'SET_AVAILABILITY_TIME',

    //Account
    GET_ACCOUNT_DETAILS: 'GET_ACCOUNT_DETAILS',
    SET_ACCOUNT_DETAILS: 'SET_ACCOUNT_DETAILS',
    CARD_DATA: 'CARD_DATA'

}